Adding system hardening guide
automotive-grade-linux/docs-agl pull request #28
Opened 2016-12-21 13:52 UTC by hammadahmedirdeto

Adding more content to the Hardening section of the security blueprint.

2016-12-21 14:33 UTC, dl9pf requested changes
TLDR:
As we have multiple options that are different for DEBUG/RELEASE, we might extend the document with a longer comparison table with all options in the end.

Also we need a full review here to not contradict subsystem like the application framework or sota/ostree.




Here is my feedback in detail:

- Disable namespace support
See: https://github.com/automotive-grade-linux/docs-agl/blob/2bf24424d624d478293c7badd7761328745df17e/docs/sec-blueprint/08-Hardening.md#disable-namespace-support

JSMoeller: IIRC Systemd and other tools require this. This needs to be checked before we recommend it!

- Disable /proc/config.gz
See: https://github.com/automotive-grade-linux/docs-agl/blob/2bf24424d624d478293c7badd7761328745df17e/docs/sec-blueprint/08-Hardening.md#disable-procconfiggz

JSMoeller: To be honest, I don't like the way this expressed. An attacker will likely know the CPU/BasicHW so not having the /proc/config.gz is a minor obstacle that costs just time IMHO. And moreover he needs to be 'on' the target already to catch that. Better differ between DEBUG and PRODUCTION build here, so push that down to the section/table with DEBUG/RELEASE. 


- Disable Sysctl syscall support
"Enabling this will result in code being included that is hard to maintain and not well tested"

JSMoeller: A little more explanation as to why - this is very brief.

- Console & Remote Access
See: https://github.com/automotive-grade-linux/docs-agl/blob/2bf24424d624d478293c7badd7761328745df17e/docs/sec-blueprint/08-Hardening.md#console--remote-access-1

JSMoeller: We are in a systemd environment, there is no inittab like this. 

- Partition Mount Options
See: https://github.com/automotive-grade-linux/docs-agl/blob/2bf24424d624d478293c7badd7761328745df17e/docs/sec-blueprint/08-Hardening.md#partition-mount-options

JSMoeller: Mount options need to be aligned with ostree recommendations/needs.

- Disable checkpoint/restore
See: https://github.com/automotive-grade-linux/docs-agl/blob/2bf24424d624d478293c7badd7761328745df17e/docs/sec-blueprint/08-Hardening.md#disable-checkpointrestore

JSMoeller: This needs to be reviewed in conjunction with the application lifecycle. If I'm not mistaken checkpoint/restore was a required feature.


- Removal or Non-Inclusion of Utilities
See: https://github.com/automotive-grade-linux/docs-agl/blob/2bf24424d624d478293c7badd7761328745df17e/docs/sec-blueprint/08-Hardening.md#removal-or-non-inclusion-of-utilities

JSMoeller: we need to double-check this list (ssh vs dropbear, init vs. systemd)

- Enable Iptables (firewall)

JSMoeller: we're using systemd, so iptables or nftables or firewalld ... we should recommend the long-term supported technique that fits into the env best.

2016-12-21 14:42 UTC, dl9pf commented
We need ATS in the reviewer list ...

2016-12-21 17:39 UTC, fulup-bzh commented
For name space or systemd it is obvious that we need them. Firewall iptables/nftables should be generated automatically by the application framework at application installation time. Removing checkpoint/restore might not be possibleto enable application pause&criu.

The list of command to include/remove seems outdated "netstat" as been replace by "ip". On system using systemd /etc/init/rcS.d /etc/init.d/inittab is empty

For the other point I agree with JSMoeller

2017-01-29 20:01 UTC, hammadahmedirdeto commented
Updated based on review comments provided.
As far as DEBUG/RELEASE kernel configuration goes, I think we should leave this document as hardening guide for production kernels and shouldn't worry about what configs a dev turns on to debug a problem.

2017-02-01 15:08 UTC, dl9pf requested changes
Hi, my 0,02:
- We need ATS to review this from a OTA perspective. Some of the changes might still collide there.

- Here is my feedback in detail:

1. Disable namespace support  -  **Done, was changed**
2. Disable /proc/config.gz
    See: https://github.com/hammadahmedirdeto/docs-agl/blob/0996761cc552e698b97f2e07f6894a46ab82345c/docs/sec-blueprint/08-Hardening.md#disable-procconfiggz
JSMoeller: To be honest, I don't like the way this expressed. An attacker will likely know the CPU/BasicHW so not having the /proc/config.gz is a minor obstacle that costs just time IMHO. And moreover he needs to be 'on' the target already to catch that. Better differ between DEBUG and PRODUCTION build here, so push that down to the section/table with DEBUG/RELEASE.
**JSMoeller: Still an issue**

3. Disable Sysctl syscall support
    "Enabling this will result in code being included that is hard to maintain and not well tested"
**JSMoeller: A little more explanation as to why - this is very brief.**

4. Console & Remote Access - **Done, was changed**

5. Partition Mount Options 
    See: https://github.com/hammadahmedirdeto/docs-agl/blob/0996761cc552e698b97f2e07f6894a46ab82345c/docs/sec-blueprint/08-Hardening.md#partition-mount-options
JSMoeller: **Mount options need to be aligned with ostree recommendations/needs.**
JSMoeller: **Add ATS to reviewers for this.**

6. Disable checkpoint/restore - **Done, was changed**

7. Removal or Non-Inclusion of Utilities
    See: https://github.com/hammadahmedirdeto/docs-agl/blob/0996761cc552e698b97f2e07f6894a46ab82345c/docs/sec-blueprint/08-Hardening.md#removal-or-non-inclusion-of-utilities
JSMoeller: we need to double-check this list (ssh vs dropbear, init vs. systemd, klog vs journalctl, stbhotplug, 

8. Enable Iptables (firewall) - **section removed, still we should recommend something**

9. disable bpf jit
  See: https://github.com/hammadahmedirdeto/docs-agl/blob/0996761cc552e698b97f2e07f6894a46ab82345c/docs/sec-blueprint/08-Hardening.md#disable-bpf-jit
JSMoeller: Unclear statement, we're not using mips. This might actually help in firewalling, so depends on choice of firewall here.

10. MIPS arch mentioned
 See: https://github.com/hammadahmedirdeto/docs-agl/blob/0996761cc552e698b97f2e07f6894a46ab82345c/docs/sec-blueprint/08-Hardening.md#kernel-hardening-1
JSMoeller: We're not using MIPS, just  x86 and arm (32/64bit) right now.


11.  –static 
 `Dynamic linking shall not be allowed. This will avoid user from replacing a library with malicious library. All libraries should be linked statically.`
 See: https://github.com/hammadahmedirdeto/docs-agl/blob/0996761cc552e698b97f2e07f6894a46ab82345c/docs/sec-blueprint/08-Hardening.md#library-linking
JSMoeller: This is **not going to fly** in the way things are done right now. Also if we are on a filesystem managed by ostree, a user cannot change a file in /lib or /usr/lib as it is under control of ostree.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +1.  After power on, the secure processor will perform the verification
The use of a 'secure processor' or of some native mechanism to achieve this operation is a strong requirement that should be explained first.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +        will restart.
I'm not sure that restarting the device is a solution! IMHO it should stop.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +    should occur then the Secure Loader will will determine the correct
typo: will will -> will

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +        (or attempted), it will initiate the reboot process.
There is probably something missing here because if the state is not changed, the reboot will reach the same conditions and an infinite loop will  aoccur (at least in my smoggy brain)

Anyway, advise of ATS is really needed here. I think that there is no conflict with their approach but I would get the feedback.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +        will initiate a reboot
or a stop

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +    that image
What is the exact meaning of "kernel image"?
Is it "the kernel" or is it "the kernel and the root kernel data/partition"?
Verifying kernel is probably not enough because further stages inside the kernel will surely need to check and validate data. To achieve it there are 2 possibililties at least: using a security processor that can validate the data or rely on a trusted data environment. The later means that the data must be validated in the same time.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
Integrity of the booted files is not clearly adressed.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +  Linux kernel, and includes the use of U-Boot as the *Stage 2*
Is U-Boot ARM specific ? Nevertheless I don't think that U-Boot is mandatory.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +CONFIG\_BOOTDELAY to -2.
Reference needed and below. I quickly dug http://www.denx.de/wiki/U-Boot/WebHome but I found nothing.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +```
It partly answers some questions I had before: this is the flat image tree that is checked.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +mass storage device.
Adding the possibility to achieve the operation from storage is not presented here.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +#define** CONFIG_ENV_IS_NOWHERE
Can you precise a location where this define is to be made

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +    stripped and removed from the kernel command line.
There is something to say about the command line: because console is prohibited, no one should be able to enter any command line (that come from uboot hardening). Nevertheless, kernel should also be hardened to disable command line arguments.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +    **RootLogin no**
SSH and or drop bear or equivalent must be removed.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +
this include tcf-agent that is currently shipped with devel version

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +linked statically.
Ideally yes but in practice this will probably not happen. Even more, because AGL allows dynamic loading, it can create bugs.
I propose to keep the idea but to rewrite as a recommandation. 
As a consequence it would be benefical for static linking to enforce the options -ffunction-sections -fdata-sections with the goal of reducing the overall size.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +|  SSH              |  NA                                       |  EXCLUDE               |  EXCLUDE                     |
no SSH in debug! I would prefer to have one.

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +|  su               |  /bin/su                                  |  EXCLUDE               |  EXCLUDE                     |
we need su in debug because AGL feature users

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +the embedded device, **should not execute** with root privileges.
Can you replace "root privileges" by "root identity or any capability"

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +If the main application are allowed to execute at elevated privileges,
you may replace "elevated privileges" by "any capability"

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +on a user with lowered privileges and all persistent resources should be
no capability

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +
by "... with such privileges" should I understand " ... without any capability" ?

2017-04-27 14:25 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +  this support as it will reduce the size of the kernel TCP/IP stack.
humm... isn't it time to switch to ipv6 and disable ipv4? (joke) I fully agree with the assertion.

2017-05-10 00:24 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +1.  After power on, the secure processor will perform the verification
Fixed

2017-05-10 00:24 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +        will restart.
Fixed

2017-05-10 00:24 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +    should occur then the Secure Loader will will determine the correct
Fixed

2017-05-10 00:26 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +        (or attempted), it will initiate the reboot process.
Been waiting for ATS review since December

2017-05-10 00:27 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +    that image
Kernel image would means the kernel and the root kernel data/partition

2017-05-10 00:27 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +        will initiate a reboot
Fixed

2017-05-10 00:27 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
I am not sure what you mean here

2017-05-10 00:29 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +  Linux kernel, and includes the use of U-Boot as the *Stage 2*
You are right. We have only looked at U-Boot for the sake of this document, mostly because of the verified boot capability.

2017-05-10 00:29 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +mass storage device.
Can you elaborate a bit more here?

2017-05-10 00:31 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +#define** CONFIG_ENV_IS_NOWHERE
Planning to add u-boot config reference as a separate pull req. Will open an issue for this.

2017-05-10 00:31 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +    **RootLogin no**
Fixed

2017-05-10 00:31 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +linked statically.
Fixed

2017-05-10 00:31 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +|  SSH              |  NA                                       |  EXCLUDE               |  EXCLUDE                     |
Fixed

2017-05-10 00:31 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +|  su               |  /bin/su                                  |  EXCLUDE               |  EXCLUDE                     |
Fixed

2017-05-10 00:32 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +the embedded device, **should not execute** with root privileges.
Fixed

2017-05-10 00:32 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +on a user with lowered privileges and all persistent resources should be
Fixed

2017-05-10 00:32 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +If the main application are allowed to execute at elevated privileges,
Fixed

2017-05-10 00:32 UTC, hammadahmedirdeto commented on docs/sec-blueprint/08-Hardening.md
> +
Fixed

2017-05-10 08:08 UTC, jobol approved these changes

2017-05-10 08:08 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
You wrote "Kernel image would means the kernel and the root kernel data/partition" so it not clearly include the the extra file system data. If I refer to FHS, it means that you verify /lib but not /usr/lib, /bin but not /usr/bin.

How to call it clearly? The platform filesystem? The user partition?

My understanding is that there is by need a separation between the root/kernel/system in  one hand and the effective installed applications running on top of that. The need comes from the fact that the system will be shared by many different vehicle but the platform is specific to models+options. The later should also be checked.

Obviously it can be made differently than the gore/kernel/root/system because the kernel is trusted and it can be used to check that data. But (1) storing signature is to be addressed somewhere (2) checking it should be specified somewhere in the blue print, why not here?

2017-05-10 08:08 UTC, jobol commented on docs/sec-blueprint/08-Hardening.md
> +mass storage device.
I was meaning that "This loader will authenticate an incoming image (USB,Serial, Network)" is closing the possibilities, maybe with right. I ask myself whether writing  "(USB,Serial, Network, Disk, Memory)" is possible or not or even merely "(USB,Serial, Network, eMMC, ...)"

2017-05-10 13:43 UTC, merged